name: 'retail_data_platform'
version: '1.0.0'
config-version: 2

profile: 'retail_platform'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
analysis-paths: ['analysis']
snapshot-paths: ['snapshots']
test-paths: ['tests']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

# Global variables
vars:
  start_date: '2020-01-01'
  end_date: '2025-12-31'

models:
  retail_data_platform:
    +materialized: view
    +on_schema_change: "append_new_columns"
    
    staging:
      +schema: 'silver'
      +tags: ['staging']
    
    intermediate:
      +schema: 'silver'
      +tags: ['intermediate']
    
    marts:
      +schema: 'gold'
      +tags: ['marts']
      
      # Databricks Delta Lake optimizations
      +file_format: delta
      +post-hook:
        - "OPTIMIZE {{ this }}"
      
      dimensions:
        +materialized: table
        +post-hook:
          - "OPTIMIZE {{ this }} ZORDER BY ({{ this.identifier }}_key)"
      
      facts:
        +materialized: incremental
        +incremental_strategy: 'merge'
        +on_schema_change: 'append_new_columns'
        +post-hook:
          - "OPTIMIZE {{ this }}"

seeds:
  retail_data_platform:
    +schema: 'bronze'
    raw:
      +column_types:
        order_id: string
        customer_id: string
        product_id: string
        order_date: string
        status: string
        total_amount: double
        customer_name: string
        email: string
        country: string
        product_name: string
        category: string
        price: double

snapshots:
  retail_data_platform:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: _loaded_at
