retail_platform:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: hive_metastore
      schema: retail_dev
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      auth_type: token
      threads: 4
    prod:
      type: databricks
      catalog: hive_metastore
      schema: retail_prod
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      auth_type: token
      threads: 4
    ci:
      type: databricks
      catalog: hive_metastore
      schema: retail_ci
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      auth_type: token
      threads: 4
