version: 2

models:
  - name: stg_orders
    description: "Staged orders with basic transformations"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      
      - name: order_date
        description: "Date the order was placed"
        tests:
          - not_null
      
      - name: status
        description: "Order status (normalized to lowercase)"
        tests:
          - accepted_values:
              values: ['pending', 'shipped', 'delivered', 'cancelled', 'returned']
      
      - name: total_amount
        description: "Total order value in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
  
  - name: stg_customers
    description: "Staged customers with cleansed data"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      
      - name: customer_name
        description: "Customer full name (trimmed)"
        tests:
          - not_null
      
      - name: email
        description: "Customer email (lowercase, trimmed)"
        tests:
          - not_null
          - unique
      
      - name: country
        description: "Customer country"
        tests:
          - not_null
  
  - name: stg_products
    description: "Staged product catalog"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      
      - name: product_name
        description: "Product name"
        tests:
          - not_null
      
      - name: category
        description: "Product category"
        tests:
          - accepted_values:
              values: ['Electronics', 'Clothing', 'Home', 'Books', 'Sports']
      
      - name: price
        description: "Product price in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
