version: 2

models:


  - name: int_order_details
    columns:
      - name: order_id
        tests: [not_null]

  - name: fct_sales
    columns:
      - name: customer_id
        tests: [not_null]
      - name: total_sales
        tests:
          - not_null
          - accepted_values:
              values: [">= 0"]
              quote: false

  - name: dim_customers
    columns:
      - name: customer_key
        tests: [not_null, unique]
